const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pageMeta={dashboard:['OPERATIONS','Command centre'],onboarding:['BUSINESS','Business setup'],workforce:['PEOPLE','People & workforce'],jobs:['OPERATIONS','Jobs & allocation'],assistant:['INTELLIGENCE','AI Operations'],video:['CONTENT','Content studio'],integrations:['SYSTEM','Connections']};
async function api(url,options={}){const r=await fetch(url,{...options,headers:{...(options.body?{'content-type':'application/json'}:{}),...options.headers}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
let noteTimer;function note(v,bad=false){const e=$('#notice')||$('#auth-message');if(!e)return;e.textContent=v;e.style.color=bad?'var(--red)':'var(--green)';clearTimeout(noteTimer);if(e.id==='notice'&&v)noteTimer=setTimeout(()=>e.textContent='',5000)}
function obj(f){return Object.fromEntries(new FormData(f))}function initials(name='User'){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'U'}
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('foai-theme',theme);$$('.theme-icon use').forEach(u=>u.setAttribute('href',theme==='dark'?'#i-sun':'#i-moon'))}
setTheme(localStorage.getItem('foai-theme')||'dark');$$('.theme-toggle').forEach(b=>b.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')));
function closeSidebar(){ $('#sidebar')?.classList.remove('open');$('#sidebar-scrim')?.classList.remove('show') }$('#open-sidebar')?.addEventListener('click',()=>{$('#sidebar').classList.add('open');$('#sidebar-scrim').classList.add('show')});$('#close-sidebar')?.addEventListener('click',closeSidebar);$('#sidebar-scrim')?.addEventListener('click',closeSidebar);
function showView(name){$$('.workspace-nav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$$('.view').forEach(v=>v.hidden=v.id!==`${name}-view`);const meta=pageMeta[name]||['WORKSPACE','Fleet Office AI'];if($('#page-eyebrow'))$('#page-eyebrow').textContent=meta[0];if($('#page-title'))$('#page-title').textContent=meta[1];closeSidebar();window.scrollTo({top:0,behavior:'smooth'})}
$$('.workspace-nav [data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>showView(b.dataset.jump));$$('[data-scroll]').forEach(b=>b.onclick=()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth',block:'start'}));
function setAuthMode(mode){const isRegister=mode==='register';$$('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===mode));$('#register-form').hidden=!isRegister;$('#login-form').hidden=isRegister;$('#auth-message').textContent='';const h=$('.auth-heading h2'),sub=$('#auth-subtitle');if(h)h.textContent=isRegister?'Create your secure account':'Welcome back';if(sub)sub.textContent=isRegister?'New here? Create the owner account first, then sign in to open your workspace.':'Already have an account? Sign in to enter your secure workspace.'}$$('[data-tab]').forEach(b=>b.onclick=()=>setAuthMode(b.dataset.tab));setAuthMode('login');
$$('[data-prompt]').forEach(b=>b.onclick=()=>{const t=$('#assistant-form textarea[name="message"]');if(t){t.value=b.dataset.prompt;t.focus()}});
async function boot(){try{const d=await api('/api/saas/me');$('#welcome').hidden=true;$('#workspace').hidden=false;$('#org-name-side').textContent=d.organisation.name;$('#user-line').textContent=`${d.user.full_name} · ${d.user.role} · ${d.user.email}`;$('#mfa-status-side').textContent=d.user.mfa_enabled?'Authenticator MFA enabled':'MFA setup recommended';$('#profile-name').textContent=d.user.full_name;$('#profile-role').textContent=d.user.role;$('#profile-avatar').textContent=initials(d.user.full_name);$('#first-name').textContent=d.user.full_name.split(/\s+/)[0]||'there';await Promise.all([loadDashboard(),loadOnboarding(),loadWorkers(),loadJobs(),loadThreads(),loadRenders()])}catch{$('#welcome').hidden=false;$('#workspace').hidden=true}}
$('#register-form').onsubmit=async e=>{e.preventDefault();const b=obj(e.target),hint=$('#password-match');if(b.password!==b.confirm_password){if(hint){hint.textContent='Passwords do not match.';hint.classList.add('error-text')}note('Passwords do not match. Please enter the same password twice.',true);e.target.elements.confirm_password.focus();return}if(hint){hint.textContent='Passwords match.';hint.classList.remove('error-text')}try{const d=await api('/api/saas/register',{method:'POST',body:JSON.stringify(b)});const email=b.email;e.target.reset();setAuthMode('login');$('#login-form').elements.email.value=email;$('#login-form').elements.password.focus();note(d.message||'Account created successfully. Sign in to open your secure workspace.')}catch(x){note(x.message,true)}};
const registerPassword=$('#register-form')?.elements.password,registerConfirm=$('#register-form')?.elements.confirm_password;function updatePasswordMatch(){const hint=$('#password-match');if(!hint||!registerConfirm)return;if(!registerConfirm.value){hint.textContent='Both passwords must match.';hint.classList.remove('error-text','success-text');return}const ok=registerPassword.value===registerConfirm.value;hint.textContent=ok?'Passwords match.':'Passwords do not match.';hint.classList.toggle('success-text',ok);hint.classList.toggle('error-text',!ok)};registerPassword?.addEventListener('input',updatePasswordMatch);registerConfirm?.addEventListener('input',updatePasswordMatch);
$('#login-form').onsubmit=async e=>{e.preventDefault();const b=obj(e.target);if(!b.mfa_code)delete b.mfa_code;try{await api('/api/saas/login',{method:'POST',body:JSON.stringify(b)});await boot()}catch(x){note(x.message,true)}};
$('#logout').onclick=async()=>{await api('/api/saas/logout',{method:'POST'});location.reload()};
async function loadDashboard(){const d=await api('/api/saas/dashboard'),m=d.metrics;$('#m-workers').textContent=m.workers;$('#m-ready').textContent=m.ready;$('#m-attention').textContent=m.attention;$('#m-jobs').textContent=m.jobs;$('#m-expiring').textContent=m.expiring;$('#nav-jobs').textContent=m.jobs;$('#briefing').textContent=m.attention||m.jobs||m.expiring?`${m.attention} worker${m.attention===1?'':'s'} need compliance attention, ${m.jobs} job${m.jobs===1?'':'s'} await allocation, and ${m.expiring} document${m.expiring===1?'':'s'} expire within 30 days.`:'No immediate workforce or allocation risks detected. Your operational foundation is clear.'}
async function loadOnboarding(){const d=await api('/api/saas/onboarding'),f=$('#onboarding-form'),p=d.profile;for(const k of ['business_type','phone','website','service_area','brand_voice','approval_mode','ai_instructions'])if(f.elements[k])f.elements[k].value=p[k]||'';f.elements.services.value=(p.services||[]).join('\n');if(f.elements.complete)f.elements.complete.checked=!!p.complete}
$('#onboarding-form').onsubmit=async e=>{e.preventDefault();const b=obj(e.target);b.services=b.services.split('\n').map(x=>x.trim()).filter(Boolean);b.complete=e.target.elements.complete.checked;await api('/api/saas/onboarding',{method:'PUT',body:JSON.stringify(b)});note('Workspace settings saved successfully.')};
async function loadWorkers(){const d=await api('/api/saas/workers');$('#workers').innerHTML=d.workers.map(w=>`<article class="row-card"><header><div><b>${esc(w.full_name)}</b><div class="muted">${esc(w.role_title)} · ${esc(w.employment_type.replaceAll('_',' '))} · Level ${w.worker_level}</div></div><span class="status ${w.approved_for_scheduling?'good':'warn'}">${w.approved_for_scheduling?'Ready to schedule':'Onboarding'}</span></header><p class="muted">Work rights: ${esc(w.work_rights_status.replaceAll('_',' '))} · Onboarding ${w.onboarding_progress}% · Passport optional</p><div class="row-actions"><button onclick="completeCompliance('${w.id}')">Test: approve compliance</button><button onclick="addSkill('${w.id}')">Add verified skill</button></div></article>`).join('')||'<div class="empty-state"><b>No workers yet</b><span>Add your first worker profile to begin onboarding and eligibility checks.</span></div>'}
$('#worker-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/saas/workers',{method:'POST',body:JSON.stringify(obj(e.target))});e.target.reset();note('Worker profile created with compliance checklist.');await Promise.all([loadWorkers(),loadDashboard()])}catch(x){note(x.message,true)}};
window.completeCompliance=async id=>{try{await api(`/api/saas/workers/${id}/compliance`,{method:'PATCH',body:JSON.stringify({work_rights_status:'verified',onboarding_progress:100})});note('Compliance marked verified for testing.');await Promise.all([loadWorkers(),loadDashboard()])}catch(x){note(x.message,true)}};
window.addSkill=async id=>{const skill=prompt('Skill name, e.g. Truck Polishing');if(!skill)return;const competency=prompt('Competency: competent, advanced or expert','competent')||'competent';try{await api(`/api/saas/workers/${id}/skills`,{method:'POST',body:JSON.stringify({skill_name:skill,competency})});note('Verified worker skill saved.')}catch(x){note(x.message,true)}};
async function loadJobs(){const d=await api('/api/saas/work-orders');$('#jobs').innerHTML=d.jobs.map(j=>`<article class="row-card"><header><div><b>${esc(j.title)}</b><div class="muted">${new Date(j.start_at).toLocaleString()} · ${j.required_workers} worker${j.required_workers===1?'':'s'} · Level ${j.required_level}+</div></div><span class="status">${esc(j.status.replaceAll('_',' '))}</span></header><p class="muted">${esc(j.address||'No address')} · Skills: ${j.required_skills.map(esc).join(', ')||'None specified'} · ${j.accepted_workers}/${j.required_workers} accepted</p><div class="row-actions"><button onclick="offerJob('${j.id}')">Find eligible workers →</button></div></article>`).join('')||'<div class="empty-state"><b>No work orders yet</b><span>Create a job and the eligibility engine will match compliant workers.</span></div>'}
$('#job-form').onsubmit=async e=>{e.preventDefault();const b=obj(e.target);b.required_skills=b.required_skills.split('\n').map(x=>x.trim()).filter(Boolean);try{await api('/api/saas/work-orders',{method:'POST',body:JSON.stringify(b)});e.target.reset();note('Work order added to the allocation pool.');await Promise.all([loadJobs(),loadDashboard()])}catch(x){note(x.message,true)}};
window.offerJob=async id=>{try{const d=await api(`/api/saas/work-orders/${id}/offer`,{method:'POST'});note(d.offered?`Offered to ${d.offered} eligible worker${d.offered===1?'':'s'}: ${d.eligible_workers.map(x=>x.full_name).join(', ')}`:'No eligible workers. Check compliance, level and verified skills.',!d.offered);await Promise.all([loadJobs(),loadDashboard()])}catch(x){note(x.message,true)}};
async function loadThreads(){const d=await api('/api/saas/ai/threads');$('#threads').innerHTML=d.threads.map(t=>`<article class="row-card"><header><div><b>${esc(t.title)}</b><div class="muted">Updated ${new Date(t.updated_at).toLocaleString()}</div></div><span class="status">Saved</span></header></article>`).join('')||'<div class="empty-state"><b>No AI Operations threads</b><span>Save an instruction to start building workspace-scoped operational memory.</span></div>'}
$('#assistant-form').onsubmit=async e=>{e.preventDefault();const d=await api('/api/saas/ai/threads',{method:'POST',body:JSON.stringify(obj(e.target))});e.target.reset();note(d.note);await loadThreads()};
$('#setup-mfa')?.addEventListener('click',async()=>{const d=await api('/api/saas/mfa/setup',{method:'POST'});$('#mfa-secret').textContent=d.secret;$('#mfa-dialog').showModal()});
$('#verify-mfa').onclick=async()=>{await api('/api/saas/mfa/verify',{method:'POST',body:JSON.stringify({code:$('#mfa-code').value})});$('#mfa-dialog').close();note('Authenticator MFA enabled.');await boot()};
async function loadRenders(){const d=await api('/api/saas/video-renders');$('#renders').innerHTML=d.jobs.map(j=>`<article class="row-card"><header><div><b>${esc(j.quality)} · ${esc(j.edit_spec.aspect_ratio)}</b><div class="muted">Saved render specification</div></div><span class="status">${esc(j.status)}</span></header></article>`).join('')||'<div class="empty-state"><b>No render specifications</b><span>Create a high-resolution output specification to populate this queue.</span></div>'}
$('#video-form').onsubmit=async e=>{e.preventDefault();const f=obj(e.target),body={quality:f.quality,edit_spec:{aspect_ratio:f.aspect_ratio,clips:[{media_id:f.media_id,start_seconds:Number(f.start_seconds),end_seconds:Number(f.end_seconds),transition:f.transition}],captions:e.target.elements.captions.checked,music:e.target.elements.music.checked,logo:e.target.elements.logo.checked,style_prompt:f.style_prompt}};const d=await api('/api/saas/video-renders',{method:'POST',body:JSON.stringify(body)});note(d.note);await loadRenders()};
boot();
