(() => {
  const $=s=>document.querySelector(s); const page=document.body.dataset.authPage;
  const api=async(url,opt={})=>{const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok){const e=new Error(r.status===429?'Please wait a few seconds before trying again.':(d.error||'The requested action could not be completed.'));e.payload=d;throw e}return d};
  const show=(text,error=false)=>{const el=$('#auth-message');if(!el)return;el.textContent=text||'';el.classList.toggle('error',Boolean(error))};
  const objectFrom=form=>Object.fromEntries(new FormData(form).entries());
  const rememberKey='gds-remember-email';

  if(page==='register'){
    const form=$('#register-form'), status=$('#business-verification-status'), verifyButton=$('#verify-business'), submit=$('#registration-submit');
    const idType=form.elements.identifier_type,idInput=form.elements.business_identifier,idLabel=$('#identifier-label'),idHelp=$('#identifier-help');
    let businessVerified=false,verifiedFingerprint='';
    const idMeta={ABN:{label:'ABN',placeholder:'11 digit ABN',help:'ABN has 11 digits. Production validation uses the Australian Business Register when configured.',max:14},ACN:{label:'ACN',placeholder:'9 digit ACN',help:'ACN has 9 digits. Production validation uses the Australian Business Register ASIC-number lookup when configured.',max:12},OTHER:{label:'Australian registration identifier',placeholder:'Enter registration identifier',help:'Other identifiers are captured for authorised manual verification where an automated registry check is unavailable.',max:80}};
    function syncIdentifier(){const m=idMeta[idType.value]||idMeta.ABN;idLabel.textContent=m.label;idInput.placeholder=m.placeholder;idInput.maxLength=m.max;idHelp.textContent=m.help;if(idType.value!=='OTHER')idInput.inputMode='numeric';else idInput.inputMode='text'}
    const fingerprint=()=>[form.elements.business_name.value.trim(),idType.value,idInput.value.replace(/\s+/g,''),form.elements.state.value,form.elements.postcode.value].join('|');
    const invalidate=()=>{businessVerified=false;verifiedFingerprint='';submit.disabled=true;status.className='identity-status';status.textContent='Business verification is required before account creation.'};
    ['business_name','business_identifier','state','postcode'].forEach(n=>form.elements[n]?.addEventListener('input',invalidate));idType?.addEventListener('change',()=>{syncIdentifier();invalidate()});syncIdentifier();
    verifyButton.onclick=async()=>{const business_name=form.elements.business_name.value.trim(),identifier_type=idType.value,business_identifier=idInput.value.trim();if(!business_name||!business_identifier){status.className='identity-status error';status.textContent=`Enter the business name and ${idMeta[identifier_type]?.label||'business identifier'} first.`;return}verifyButton.disabled=true;verifyButton.textContent='Checking…';try{const d=await api('/api/saas/business/verify',{method:'POST',body:JSON.stringify({business_name,identifier_type,business_identifier})});businessVerified=true;verifiedFingerprint=fingerprint();submit.disabled=false;status.className='identity-status verified';const loc=[d.business.state,d.business.postcode].filter(Boolean).join(' '),label=d.business.identifier_type||identifier_type;status.textContent=`${label==='OTHER'?'Captured for authorised review':'Verified'} ${label} ${d.business.identifier||business_identifier}${d.business.legal_name?` · ${d.business.legal_name}`:''}${loc?` · ${loc}`:''}${d.test_mode?' · LOCAL TEST MODE':''}`;}catch(e){businessVerified=false;verifiedFingerprint='';submit.disabled=true;status.className='identity-status error';status.textContent=e.message}finally{verifyButton.disabled=false;verifyButton.textContent='Check business identity'}};
    const pass=form.elements.password,confirm=form.elements.confirm_password,meter=$('#password-meter'),hint=$('#password-hint');
    function updatePassword(){const v=pass.value;let score=0;if(v.length>=14)score++;if(/[A-Z]/.test(v)&&/[a-z]/.test(v))score++;if(/\d/.test(v))score++;if(/[^A-Za-z0-9]/.test(v))score++;meter.dataset.score=String(score);if(confirm.value)hint.textContent=pass.value===confirm.value?'Passwords match.':'Passwords do not match.';else hint.textContent='Use at least 14 characters; a passphrase is recommended.';hint.style.color=confirm.value&&pass.value!==confirm.value?'var(--red)':''}
    pass.addEventListener('input',updatePassword);confirm.addEventListener('input',updatePassword);
    form.onsubmit=async e=>{e.preventDefault();show('');if(!businessVerified||verifiedFingerprint!==fingerprint()){invalidate();show('Verify the current Australian business identity before continuing.',true);status.scrollIntoView({behavior:'smooth',block:'center'});return}if(pass.value!==confirm.value){show('Passwords do not match.',true);confirm.focus();return}if(!form.elements.accept_terms.checked){show('Please accept the Terms of Service and Privacy Notice.',true);return}const b=objectFrom(form);b.accept_terms=true;b.terms_version='prelaunch-2026-09-16-v11';submit.disabled=true;submit.textContent='Securing verification…';try{const d=await api('/api/saas/registration/start',{method:'POST',body:JSON.stringify(b)});sessionStorage.setItem('gds-pending-registration',JSON.stringify({pending_id:d.pending_id,email:d.email,phone:d.phone,business:d.business,test_mode:d.test_mode,test_codes:d.delivery?.test_codes||null,raw_email:b.email}));location.href='verify-account.html'}catch(err){show(err.message,true);submit.disabled=false;submit.textContent='Join your AI Office →'}};
  }

  if(page==='verify'){
    const raw=sessionStorage.getItem('gds-pending-registration');if(!raw){location.href='create-account.html';return}let state;try{state=JSON.parse(raw)}catch{location.href='create-account.html';return}
    $('#verification-destination').textContent=`Enter the 6-digit codes sent to ${state.email} and ${state.phone}.`;
    if(state.test_mode&&state.test_codes){const box=$('#test-codes');box.hidden=false;box.innerHTML=`<b>LOCAL TEST MODE</b><br>Email code: <strong>${state.test_codes.email}</strong> · SMS code: <strong>${state.test_codes.sms}</strong><br><small>Test codes are exposed only when SAAS_VERIFICATION_TEST_MODE=1 outside production.</small>`}
    const form=$('#verification-form'),button=$('#verification-submit');form.onsubmit=async e=>{e.preventDefault();show('');const b=objectFrom(form);b.pending_id=state.pending_id;button.disabled=true;button.textContent='Verifying…';try{const d=await api('/api/saas/registration/verify',{method:'POST',body:JSON.stringify(b)});sessionStorage.removeItem('gds-pending-registration');sessionStorage.setItem('gds-new-email',state.raw_email||'');sessionStorage.setItem('gds-first-login-tour','1');location.href='sign-in.html?created=1'}catch(err){show(err.message,true);button.disabled=false;button.textContent='Complete secure verification →'}};
    document.querySelectorAll('[data-resend]').forEach(btn=>btn.onclick=async()=>{btn.disabled=true;try{const d=await api('/api/saas/registration/resend',{method:'POST',body:JSON.stringify({pending_id:state.pending_id,channel:btn.dataset.resend})});show(d.message||'A new code was issued.');if(d.test_code){const box=$('#test-codes');box.hidden=false;box.innerHTML+=`<br>New ${btn.dataset.resend.toUpperCase()} code: <strong>${d.test_code}</strong>`}}catch(err){show(err.message,true)}finally{btn.disabled=false}});
  }

  if(page==='login'){
    const form=$('#login-form'),remember=form.elements.remember_email;const newEmail=sessionStorage.getItem('gds-new-email'),saved=localStorage.getItem(rememberKey);if(newEmail){form.elements.email.value=newEmail;show('Your verified workspace is ready. Sign in to continue.');sessionStorage.removeItem('gds-new-email')}else if(saved){form.elements.email.value=saved;remember.checked=true}
    const pending=sessionStorage.getItem('gds-pending-registration');if(pending)$('#pending-verification').hidden=false;
    form.onsubmit=async e=>{e.preventDefault();show('');const b=objectFrom(form);delete b.remember_email;if(!b.mfa_code)delete b.mfa_code;try{await api('/api/saas/login',{method:'POST',body:JSON.stringify(b)});if(remember.checked)localStorage.setItem(rememberKey,form.elements.email.value.trim());else localStorage.removeItem(rememberKey);if(sessionStorage.getItem('gds-first-login-tour')==='1'){sessionStorage.setItem('gds-run-tour','1');sessionStorage.removeItem('gds-first-login-tour')}location.href='workspace.html#dashboard'}catch(err){if(err.payload?.mfa_required){$('#mfa-details').open=true;form.elements.mfa_code.focus()}show(err.message,true)}};
  }
})();
