(() => {
  const topics = [
    {id:'overview',title:'What is Super Pro AI Office Manager?',keys:['what is','what does','overview','about','product','software','gds','wizard','office manager','ai office','platform'],answer:'Super Pro AI Office Manager is an AI-assisted operating system for service businesses. It brings enquiries, customers, CRM, quotes, bookings, jobs, workforce, communications, content workflows, integrations and owner-approved AI actions into one connected workspace.',next:['What are the main modules?','Who is Super Pro AI Office Manager built for?','How do I get started?']},
    {id:'modules',title:'What is included?',keys:['module','modules','feature','features','included','products','tools','capabilities','everything included'],answer:'The product is organised around a Command Centre, Business Setup, People & Workforce, Jobs & Allocation, AI Operations, Content Studio, Connections, Plans & Billing, customer/lead workflows and the legacy operations tools already present in this build. Global AI Search and the Super Pro Co-pilot help users find the right area quickly. A Trust & Governance module adds role-aware policies, protected complaints, security alerts and tamper-evident audit evidence.',next:['Tell me about AI Operations','How does workforce management work?','What can Content Studio do?']},
    {id:'ai',title:'AI and automation',keys:['ai','artificial intelligence','automation','assistant','copilot','agent','automatic','workflow','smart'],answer:'The AI layer helps explain the product, draft and organise work, prepare next actions, surface attention items, build content specifications and navigate the workspace. Consequential external actions remain approval-controlled. Live generative responses require an approved AI provider or local model connection; the built-in product guide works without one.',next:['What can AI do automatically?','What requires owner approval?','How does the AI co-pilot work?']},
    {id:'receptionist',title:'AI receptionist and communications',keys:['phone','call','receptionist','voice','sms','whatsapp','message','email','telnyx','1300','number','answer calls','call handling'],answer:'The communications architecture supports AI receptionist workflows, calls, SMS, email and connected messaging channels. Telnyx is the current telephony target, while WhatsApp/Meta, email and other channels are designed to feed the Universal Inbox and CRM. A channel is never represented as live until credentials, permissions and a connection test succeed.',next:['Can it use a 1300 number?','How are calls saved to CRM?','Which messaging channels can connect?']},
    {id:'crm',title:'Customers, leads and follow-up',keys:['crm','lead','customer','enquiry','inquiry','follow up','follow-up','sales','quote recovery','review','referral','pipeline'],answer:'The customer side is designed around one timeline: capture enquiries and lead source, prepare responses, track customer context, follow up, recover unaccepted quotes, trigger review/referral workflows and connect outcomes back to bookings, jobs and revenue.',next:['How does lead follow-up work?','Can it help recover quotes?','Does it keep customer history?']},
    {id:'jobs',title:'Jobs, booking and workforce',keys:['job','booking','schedule','dispatch','allocate','employee','worker','staff','team','workforce','roster','crew','skills'],answer:'You can create worker profiles, track skills and work-right readiness, create work orders, and match eligible workers to jobs. The owner can also be added as a worker, so the same workflow can support a solo operator or a larger team.',next:['Can I add unlimited employees?','How does job allocation work?','What workforce compliance is tracked?']},
    {id:'content',title:'Content Studio',keys:['content','video','reel','tiktok','instagram','facebook','youtube','render','social','caption','trend','transition','editing'],answer:'Content Studio organises previous media and recordings, creates platform-aware render specifications, suggests hooks, transitions, captions, safe-zone framing and creative improvements, and stores render jobs. Live trends, publishing or account analytics only activate after the relevant official platform connection is authorised.',next:['Can it suggest transitions automatically?','Does it support TikTok and Reels?','How are live trends handled?']},
    {id:'search',title:'Search and voice navigation',keys:['search','find','where','navigate','voice search','how do i find','feature','command palette','speak'],answer:'Inside the workspace, Global AI Search accepts typed or spoken requests such as “add a worker”, “show jobs”, “open Content Studio” or “where do I connect WhatsApp?”. It returns matching workspace areas plus product guidance, so users do not need to remember menu names.',next:['Can I use voice inside the workspace?','Show me how the co-pilot navigates','What can I search for?']},
    {id:'industries',title:'Who it is for',keys:['industry','industries','tradie','trades','accountant','accounting','hairdresser','salon','real estate','property','service business','business type','plumber','electrician','cleaner'],answer:'Super Pro AI Office Manager is designed for service businesses rather than one narrow trade. Starter templates cover trades and field services, accounting/professional services, salons and hairdressers, real estate/property services, mobile/appointment services and custom service businesses. Each template can suggest relevant services, workflow and AI instructions, then the owner edits them.',next:['How would it work for a tradie?','How would it work for a salon?','Can I create my own business type?']},
    {id:'security',title:'Security and verification',keys:['security','secure','verification','abn','email verification','mobile verification','mfa','privacy','hack','scam','tenant','otp','password'],answer:'New Australian workspaces support ABN or ACN business verification plus email and Australian-mobile one-time codes before account creation. Sign-in uses HTTP-only sessions, rate limiting, tenant isolation, optional authenticator MFA and temporary lockout after repeated failed passwords. Production ABN/ACN verification requires an Australian Business Register web-services GUID.',next:['Why verify both email and mobile?','Does it store my password in the browser?','How does MFA work?']},
    {id:'plans',title:'Plans and trial',keys:['price','pricing','plan','plans','cost','trial','starter','operations','scale','subscription','billing','monthly','annual'],answer:'The current test build offers a 14-day trial with no card required. Indicative plans shown are Starter A$99/month + GST, Operations A$199/month + GST and Scale A$349/month + GST. Paid billing remains disabled until a payment provider, final commercial terms and explicit customer authority are configured.',next:['What is in Starter?','What is in Operations?','When does billing start?']},
    {id:'integrations',title:'Integrations',keys:['integration','connect','meta','facebook','instagram','whatsapp','tiktok','youtube','google','xero','quickbooks','api','connection'],answer:'The platform is designed to connect communications, social, telephony, email, Meta/Facebook/Instagram, WhatsApp, TikTok, YouTube, Snapchat, X, Google Business, websites and later accounting/payment tools through approved APIs. Customers do not enter developer secrets; app-level credentials stay protected server-side and authorised account connection uses provider consent flows. Super Pro AI Office Manager owns the workflow and customer context while specialised providers handle regulated or platform-specific transport.',next:['How do I connect WhatsApp?','Does it connect to YouTube?','Are integrations already live?']},
    {id:'approvals',title:'Human control',keys:['approval','control','human','permission','automatic send','autonomous','risk','send automatically','approve'],answer:'AI assistance is intentionally approval-aware. A workspace can require approval for everything, for external actions, or use custom rules. Messaging, allocations, payments and other consequential actions should not silently execute outside the permissions the owner sets.',next:['What does external-action approval mean?','Can I change approval rules later?','What actions should stay manual?']},
    {id:'setup',title:'Getting started',keys:['start','setup','create account','sign up','register','onboarding','first time','walkthrough','tutorial','getting started'],answer:'Start on the product introduction, ask the AI guide anything you need, then create a verified workspace. After business-identifier, email and mobile verification, sign in. The first login launches a guided walkthrough of Command Centre, Business Setup, Workforce, Jobs, AI Operations, Content Studio, Connections, Trust & Governance and Billing.',next:['What do I need to create an account?','What happens after sign-in?','Can I replay the tutorial?']},
    {id:'customise',title:'Customisation',keys:['customise','customize','custom','my business','brand voice','instructions','settings','tailor','tailored'],answer:'Business Setup lets the owner define business type, services, service area, brand voice, approval mode and permanent AI instructions. Industry templates only prefill sensible starting points and do not silently overwrite information the user has already entered.',next:['What can I customise?','How do industry templates work?','Can I set permanent AI instructions?']},
    {id:'data',title:'Data and privacy',keys:['data','privacy','store data','customer data','employee data','retention','delete','export','backup'],answer:'The architecture is organisation-scoped and designed around tenant isolation, authenticated sessions, role-based access, audit-ready actions, a tamper-evident governance ledger and controlled handling of customer/workforce information. Final production retention, export/deletion, backup and regional-data policies require completion before commercial launch.',next:['Is each business data isolated?','What workforce data is sensitive?','What still needs production review?']},
    {id:'mobile',title:'Desktop and mobile use',keys:['mobile','phone app','responsive','tablet','desktop','field','onsite','on site'],answer:'The interface is responsive and designed desktop-first for office operations, with mobile-friendly layouts for field use. Voice search and microphone features depend on browser support and microphone permission; Chrome and Edge provide the best local test experience.',next:['Can field staff use it?','Does voice work on every browser?','What is desktop-first?']},
    {id:'value',title:'Why businesses use it',keys:['why','benefit','benefits','value','save time','growth','grow','worth','problem solve','replace'],answer:'The product is intended to reduce fragmentation: instead of switching between disconnected customer, job, team, content and communication tools, the business works from one operational context. The practical value is faster follow-up, clearer ownership of work, fewer missed tasks and more consistent customer handling—without handing consequential decisions to AI by default.',next:['How does it help get more leads?','How does it save admin time?','What stays under human control?']},
    {id:'governance',title:'Trust, governance and complaints',keys:['governance','complaint','complaints','help desk','support desk','rights','policy','policies','procedure','grievance','complaint officer','trust center','legal governance','audit log','activity log'],answer:'The Trust & Governance layer gives customers, workers and staff an immediate Help & Complaint Desk, role-aware policies, protected escalation, case references, senior-only security/audit views and human review for consequential matters. Serious privacy, security, safety, fraud, staff-conduct or legal cases can trigger configured in-app, email, SMS and critical voice escalation.',next:['Who can see activity logs?','How are confidential complaints routed?','What policies can staff acknowledge?']},
    {id:'audit',title:'Tamper-evident audit and access',keys:['audit','audit trail','activity log','immutable','blockchain','tamper','tamper proof','hash','ledger','owner access','manager access','who can see logs'],answer:'Super Pro AI Office Manager uses organisation-scoped audit events plus an append-only governance ledger with linked cryptographic hashes. That gives tamper evidence without putting private customer information on a public blockchain. Organisation-wide audit and governance evidence is restricted server-side to authorised senior roles such as owner, admin, manager or director.',next:['Is this a public blockchain?','Can employees see owner logs?','What happens if someone changes a record?']},
    {id:'complaint-routing',title:'Confidential complaints and escalation',keys:['confidential complaint','complaint against manager','whistleblower','whistleblowing','report manager','serious complaint','escalation','fraud report','security incident','privacy complaint'],answer:'A complaint can request confidential routing. Cases about privacy, security, fraud/scams, safety, staff conduct or legal correspondence receive higher-risk triage and can bypass a conflicted manager. Statutory whistleblower protection is not automatically promised: eligibility and legal protections depend on the person, subject matter, recipient and circumstances.',next:['Will the owner be alerted?','Can a manager see a complaint about them?','How are whistleblower reports different?']},
    {id:'self-service-integrations',title:'Self-service platform connections',keys:['self service','oauth','api key','developer key','connect social media','all social platforms','snapchat','twitter','x','facebook','meta','instagram','youtube','website','customer should not setup api'],answer:'Customers should not paste developer API secrets. The Connections hub lets them choose the business platforms they want, identify their business account and prepare the connection. Super Pro AI Office Manager keeps app-level provider credentials server-side and uses provider-authorised OAuth/consent flows when those connectors are configured.',next:['Which platforms are included?','Do customers need API keys?','Can all content be managed from one place?']},
    {id:'manual',title:'Digital user manual and live map',keys:['user manual','manual','digital manual','live map','application map','where am i','what do i do next','navigation map','guided help'],answer:'The Digital User Manual is role-aware and follows your current workspace location. It highlights the active area on a visual application map, explains what the page is for, suggests the next permitted actions and can take you directly to the relevant workspace section or Help Desk.',next:['Open the digital user manual','What should I do next?','Can staff see different guidance?']},
    {id:'key-control',title:'Platform key control',keys:['keys','api keys','secret','secrets','key control','one time key','platform credentials','customer api key','developer secret'],answer:'Super Pro AI Office Manager uses platform-managed application credentials. The operator configures each provider credential once in the protected server or production secret manager; customer workspaces never receive the raw secret. Each customer then authorises only their own business account through the provider connection flow, keeping platform keys under operator control.',next:['Do customers see API keys?','Where should production secrets be stored?','How do customers connect their accounts?']},
    {id:'finance-intelligence',title:'Expenses and profit intelligence',keys:['expense','expenses','profit','net profit','overhead','insurance','stock cost','job profit','costs'],answer:'The Office Manager can record business expenses such as materials, stock, supplied services, subscriptions, insurance and overheads. Costs can be linked to jobs so authorised users can compare recorded revenue and expenses for job-level and overall net-profit reporting. Tax and accounting treatment still requires professional review.',next:['Can I link an expense to a job?','Who can see profit information?','Can AI categorise expenses?']},
    {id:'quality-loop',title:'Maker and checker quality loop',keys:['maker checker','checker','verifier','quality loop','loop engineering','verify ai','ai quality'],answer:'Super Pro separates creation from verification. A maker prepares output, a separate checker tests explicit quality and safety criteria, the verdict is recorded, and failed checks are revised instead of silently promoted. Consequential actions still require authorised human review.',next:['Where are checker results stored?','Can the checker send actions?','How does the quality ratchet work?']},
    {id:'referrals',title:'Referral rewards and attribution',keys:['referral','refer','reward','discount','referral code','invite business'],answer:'Each subscribed organisation can have an original referral code. Referred accounts can be attributed back to that original source while reward eligibility and amounts remain controlled by published program rules. The software does not promise a reward before qualification.',next:['Where do I enter a referral code?','Can I see referred businesses?','How are rewards approved?']},
    {id:'search-visibility',title:'SEO, GEO and AEO visibility',keys:['seo','geo','aeo','search','answer engine','generative engine','google','bing','indexnow'],answer:'The public product experience includes crawl controls, sitemap, canonical metadata, structured data, an Answer Center, IndexNow readiness and a Search Visibility Centre. Private workspaces remain excluded from crawling. GEO/AEO features improve answer-ready, evidence-based public information but do not guarantee rankings or AI citations.',next:['What is the Answer Center?','Are private pages indexed?','What is IndexNow?']},
    {id:'install-app',title:'Install on desktop, tablet and mobile',keys:['download','install','mobile app','desktop app','tablet','pwa','add to home screen'],answer:'Super Pro includes installable Progressive Web App support for compatible desktop and mobile browsers. It does not claim an app-store listing until one is actually published. Authenticated workspace data is intentionally excluded from the public offline cache.',next:['How do I install it?','Does it work on mobile?','Is private data cached offline?']},
    {id:'limitations',title:'What is not live yet',keys:['not working','not live','limitation','limitations','available now','production ready','ready','real ai','live ai'],answer:'This is a pre-launch product build. Core workspace flows, local product guidance and the secure-registration architecture are implemented for testing, while real ABR lookup, email/SMS delivery, telephony, social publishing, live account analytics, paid billing and any live generative model require their production credentials/providers and final operational review.',next:['What can I test locally now?','What credentials are needed for production?','Which integrations still need connection?']}
  ];

  const clean=value=>String(value||'').toLowerCase().replace(/[^a-z0-9+&\s-]/g,' ').replace(/\s+/g,' ').trim();
  const words=value=>clean(value).split(' ').filter(Boolean);
  function rank(query,topic){
    const q=clean(query); if(!q) return 0; let score=0;
    for(const key of topic.keys){const k=clean(key);if(q===k)score+=28;else if(q.includes(k))score+=10+Math.min(6,words(k).length*2);else{const ks=words(k).filter(w=>w.length>2);score+=ks.filter(w=>q.includes(w)).length*2}}
    score+=words(topic.title).filter(w=>w.length>3&&q.includes(w)).length*2;
    return score;
  }
  function conversational(query){
    const q=clean(query);
    if(/^(hi|hello|hey|good morning|good afternoon|good evening)\b/.test(q))return {text:'Welcome to Super Pro AI Office Manager. I can explain the product like a product specialist—features, plans, setup, security, AI, calls and messages, jobs, workforce, Content Studio, integrations or how it could fit your type of service business.',topic:'greeting',suggestions:['What can Super Pro AI Office Manager do?','How could it fit my business?','How secure is account creation?']};
    if(/\b(thanks|thank you|cheers)\b/.test(q))return {text:'You’re welcome. If there is anything you still want to understand before creating an account, ask me directly and I’ll explain the relevant part of Super Pro AI Office Manager.',topic:'thanks',suggestions:['Show me the main modules','Explain the trial and plans','How do I create a secure account?']};
    return null;
  }
  function answer(query,context='public',previousTopic=''){
    const q=clean(query);
    if(!q)return {text:'Ask me anything about Super Pro AI Office Manager—features, AI, plans, security, setup, industries, jobs, calls, content or integrations.',topic:'overview',suggestions:['What can Super Pro AI Office Manager do?','How does secure account verification work?','How would it fit my business?']};
    const chat=conversational(q); if(chat)return chat;
    const followUp=/^(tell me more|more|more detail|explain more|how exactly|what else|continue|go on)\b/.test(q);
    if(followUp&&previousTopic){const prev=topics.find(t=>t.id===previousTopic);if(prev)return {text:`${prev.answer} If you want, ask about a specific part of that workflow and I’ll narrow it down.`,topic:prev.id,suggestions:prev.next||['How do I set this up?','What does the customer see?','What requires approval?']};}
    const ranked=topics.map(t=>({topic:t,score:rank(q,t)})).sort((a,b)=>b.score-a.score),best=ranked[0];
    if(best.score<=1)return {text:'I can answer questions about Super Pro AI Office Manager itself—what it does, how it fits different service businesses, plans, setup, security, AI, CRM, workforce, jobs, calls/messages, Content Studio, integrations and workspace navigation. Tell me what you want your business to achieve, or name the feature you are unsure about, and I’ll connect it to the relevant part of the product.',topic:'fallback',suggestions:['How could this reduce office admin?','Can it manage employees and jobs?','Can AI answer calls and messages?']};
    let text=best.topic.answer;
    const second=ranked.find((x,i)=>i>0&&x.score>=Math.max(7,best.score*.55));
    if(second&&second.topic.id!==best.topic.id)text+=` ${second.topic.answer}`;
    if(context==='workspace')text+=' I can also take you to the closest workspace area.';
    return {text,topic:best.topic.id,suggestions:best.topic.next||ranked.slice(1,4).filter(x=>x.score>1).map(x=>x.topic.title)};
  }

  const navigation=[
    {view:'dashboard',label:'Command centre',keys:['dashboard','command centre','home','overview','attention','brief']},
    {view:'onboarding',label:'Business setup',keys:['setup','business setup','profile','industry','services','approval settings','brand voice']},
    {view:'workforce',label:'People & workforce',keys:['worker','employee','staff','team','workforce','people','compliance','add employee']},
    {view:'jobs',label:'Jobs & allocation',keys:['job','booking','allocate','allocation','schedule','dispatch','work order']},
    {view:'assistant',label:'AI Operations',keys:['ai operations','assistant','ai task','operations task','memory','instructions']},
    {view:'video',label:'Content studio',keys:['content','video','reel','render','social','media','tiktok','youtube']},
    {view:'integrations',label:'Connections',keys:['integration','connection','connect','whatsapp','tiktok','facebook','instagram','youtube','snapchat','twitter','x','email','sms','phone','telnyx']},
    {view:'governance',label:'Trust & governance',keys:['governance','trust','complaint','complaints','help desk','policy','policies','audit','security alert','rights','legal','activity log']},
    {view:'manual',label:'Digital user manual',keys:['manual','user manual','guide','live map','application map','help me','where am i','what next']},
    {view:'billing',label:'Plans & billing',keys:['billing','plan','subscription','trial','price','pricing']}
  ];
  function findActions(query){const q=clean(query);return navigation.map(n=>({...n,score:n.keys.reduce((s,k)=>s+(q.includes(clean(k))?10:0),0)+(q.includes(clean(n.label))?15:0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score)}
  function detectLanguage(text){const t=String(text||'');if(/[ےںٹڈڑھچپگژکگیہ]/.test(t)||/(?:^|\s)(?:ہے|ہیں|میں|آپ|کیا|کیسے|نہیں|اور|یہ|وہ|جو|کو|سے|کا|کی)(?:\s|$)/.test(t))return 'ur';if(/[\u0600-\u06FF]/.test(t))return 'ar';if(/[\u0900-\u097F]/.test(t))return 'hi';if(/[\u0A00-\u0A7F]/.test(t))return 'pa';if(/[\u4E00-\u9FFF]/.test(t))return 'zh';if(/[\u3040-\u30FF]/.test(t))return 'ja';if(/[\uAC00-\uD7AF]/.test(t))return 'ko';if(/[\u0980-\u09FF]/.test(t))return 'bn';if(/[\u0B80-\u0BFF]/.test(t))return 'ta';if(/[áéíóúñ¿¡]/i.test(t))return 'es';if(/[àâçéèêëîïôûùüÿœ]/i.test(t))return 'fr';return 'en'}
  async function answerAsync(query,context='public',previousTopic='',language='auto'){
    const local=answer(query,context,previousTopic);try{const r=await fetch('/api/product-guide/answer',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({question:String(query||''),context,language})});const d=await r.json().catch(()=>({}));if(r.ok&&d.text)return {...local,text:d.text,language:d.language||detectLanguage(query),source:d.source||'server'}}catch{}return {...local,language:detectLanguage(query),source:'browser-fallback'}
  }
  window.GDSProductGuide={topics,answer,answerAsync,findActions,clean,detectLanguage};
})();
