(()=>{
  if(document.querySelector('#gds-global-support'))return;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const shell=document.createElement('div');shell.id='gds-global-support';
  shell.innerHTML=`<button class="gds-support-launch" type="button"><span>24/7</span><div>Help & complaints<small>Support · rights · escalation</small></div></button>
  <section class="gds-support-panel" hidden aria-label="Super Pro AI Office Manager Help Desk"><header class="gds-support-head"><div><b>Super Pro Help & Complaint Desk</b><small>Immediate intake · protected routing · human escalation</small></div><button class="gds-support-close" type="button" aria-label="Close support">×</button></header><div class="gds-support-body">
  <div class="gds-support-actions"><button type="button" data-support-mode="help" class="active">Need help</button><button type="button" data-support-mode="complaint">Make a complaint</button><button type="button" data-support-mode="security">Report security/privacy</button></div>
  <div class="gds-support-urgent"><strong>Emergency:</strong> this desk is not an emergency service. If there is immediate danger, contact the appropriate emergency service. Serious security, privacy, safety or legal matters are escalated for authorised human review.</div>
  <details class="gds-support-track"><summary>Track an existing case</summary><form class="gds-track-form"><div class="gds-support-grid"><label><span>Case reference</span><input name="reference" placeholder="SPAI-260916-ABC123" required></label><label><span>Private access key or email</span><input name="access" placeholder="Access key (preferred) or email" required></label></div><button type="submit">Check status</button><p class="gds-track-message" aria-live="polite"></p></form></details>
  <form class="gds-support-form"><div class="gds-support-grid"><label><span>I am a</span><select name="reporter_type"><option value="customer">Customer</option><option value="employee">Employee</option><option value="worker">Worker</option><option value="contractor">Contractor</option><option value="manager">Manager</option><option value="owner">Owner</option><option value="public">Public / visitor</option><option value="other">Other</option></select></label><label><span>Category</span><select name="category"><option value="general_support">General help</option><option value="technical">Technical issue</option><option value="billing">Billing / account</option><option value="service_complaint">Service complaint</option><option value="staff_conduct">Staff conduct</option><option value="workplace">Workplace concern</option><option value="privacy">Privacy / personal information</option><option value="security">Security / unauthorised access</option><option value="fraud_scam">Fraud / scam concern</option><option value="safety">Safety issue</option><option value="legal_notice">Legal / regulator correspondence</option><option value="accessibility">Accessibility</option><option value="data_request">Access / correction / data request</option><option value="other">Other</option></select></label></div>
  <div class="gds-support-grid"><label><span>Your name</span><input name="reporter_name" required maxlength="150" autocomplete="name" placeholder="Full name"></label><label><span>Concern involves <small>optional conflict control</small></span><select name="reported_party_role"><option value="none">No specific staff role</option><option value="employee">Employee / staff member</option><option value="worker">Worker</option><option value="contractor">Contractor</option><option value="supervisor">Supervisor</option><option value="manager">Manager</option><option value="owner">Owner / principal</option><option value="other">Other</option></select></label></div><div class="gds-support-grid"><label><span>Email</span><input name="reporter_email" type="email" autocomplete="email" placeholder="you@example.com"></label><label><span>Mobile / phone</span><input name="reporter_phone" autocomplete="tel" placeholder="04xx xxx xxx"></label></div><label class="gds-support-check"><input name="anonymous" type="checkbox"><span>Use protected / anonymous intake. Your name will not be attached to the case record. Optional contact details may still be provided for follow-up. This option does not guarantee statutory whistleblower status or absolute technical anonymity.</span></label><label><span>Subject</span><input name="subject" required minlength="4" maxlength="200" placeholder="Briefly describe the issue"></label><label><span>Details</span><textarea name="details" required minlength="10" maxlength="12000" rows="5" placeholder="Tell us what happened, what you need, and any important dates or reference numbers."></textarea></label><label><span>Evidence / attachments <small>up to 5 files · 8 MB each</small></span><input name="files" type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf,text/plain,audio/*"></label><div class="gds-support-grid"><button class="gds-support-record" type="button">◉ Record voice note</button><span class="gds-support-record-status">Optional · browser permission required</span></div><label class="gds-support-check"><input name="confidential" type="checkbox"><span>Request confidential routing. Access is restricted according to case type, conflict controls and authorised role. Statutory whistleblower protections are not automatically created by selecting this option.</span></label><button class="gds-support-submit" type="submit">Submit securely & create reference</button><p class="gds-support-message" aria-live="polite"></p></form>
  <div class="gds-support-links"><a href="/saas/trust-center.html" target="_blank">Trust Center</a><a href="/saas/terms.html" target="_blank">Terms</a><a href="/saas/privacy.html" target="_blank">Privacy</a><a href="/saas/trust-center.html#complaints" target="_blank">Complaints process</a><a href="/saas/trust-center.html#ai" target="_blank">AI governance</a></div><p class="gds-support-safety"><strong>Legal notice:</strong> policy templates and automated triage are operational tools, not legal advice. Applicable rights and statutory processes depend on the organisation, role, jurisdiction and facts.</p>
  </div></section>`;
  document.body.append(shell);
  const launch=shell.querySelector('.gds-support-launch'),panel=shell.querySelector('.gds-support-panel'),close=shell.querySelector('.gds-support-close'),form=shell.querySelector('.gds-support-form'),msg=shell.querySelector('.gds-support-message');
  const trackForm=shell.querySelector('.gds-track-form'),trackMsg=shell.querySelector('.gds-track-message');
  const embeddedPlacement=document.body.dataset.supportPlacement==='nav';if(embeddedPlacement)launch.hidden=true;
  window.GDSSupport={open(){panel.hidden=false;launch.hidden=true;form.querySelector('input[name="reporter_name"]')?.focus()},close(){panel.hidden=true;if(!embeddedPlacement)launch.hidden=false}};
  if(trackForm)trackForm.onsubmit=async e=>{e.preventDefault();trackMsg.textContent='Checking…';const ref=String(trackForm.elements.reference.value||'').trim();const access=String(trackForm.elements.access.value||'').trim();const isEmail=access.includes('@');const qs=new URLSearchParams(isEmail?{email:access}:{access_token:access});try{const r=await fetch(`/api/support/cases/${encodeURIComponent(ref)}?${qs}`,{credentials:'same-origin'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Case could not be found.');trackMsg.innerHTML=`<strong>${esc(d.case.reference_code)}</strong> · ${esc(d.case.status)} · ${esc(d.case.severity)}<br>${esc(d.case.triage_summary||'')}`;}catch(err){trackMsg.textContent=err.message;}};
  let voiceBlob=null,recorder=null,voiceChunks=[];const recordButton=shell.querySelector('.gds-support-record'),recordStatus=shell.querySelector('.gds-support-record-status');
  if(recordButton){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){recordButton.disabled=true;recordStatus.textContent='Voice recording is not supported in this browser.'}else{recordButton.onclick=async()=>{try{if(recorder&&recorder.state==='recording'){recorder.stop();return}const stream=await navigator.mediaDevices.getUserMedia({audio:true});voiceChunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data?.size)voiceChunks.push(e.data)};recorder.onstop=()=>{voiceBlob=new Blob(voiceChunks,{type:recorder.mimeType||'audio/webm'});stream.getTracks().forEach(t=>t.stop());recordButton.textContent='✓ Voice note recorded';recordStatus.textContent=`${Math.max(1,Math.round(voiceBlob.size/1024))} KB ready to attach`;recordButton.classList.remove('recording')};recorder.start();recordButton.textContent='■ Stop recording';recordStatus.textContent='Recording…';recordButton.classList.add('recording')}catch(err){recordStatus.textContent='Microphone permission was not available.'}}}}
  launch.onclick=()=>window.GDSSupport.open();close.onclick=()=>window.GDSSupport.close();document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)window.GDSSupport.close()});
  shell.querySelectorAll('[data-support-mode]').forEach(btn=>btn.onclick=()=>{shell.querySelectorAll('[data-support-mode]').forEach(x=>x.classList.toggle('active',x===btn));const cat=form.elements.category;if(btn.dataset.supportMode==='complaint')cat.value='service_complaint';if(btn.dataset.supportMode==='security')cat.value='security';if(btn.dataset.supportMode==='help')cat.value='general_support'});
  const anonymousToggle=form.elements.anonymous,nameInput=form.elements.reporter_name;
  if(anonymousToggle)anonymousToggle.onchange=()=>{const on=anonymousToggle.checked;nameInput.required=!on;nameInput.disabled=on;if(on)nameInput.value='';};
  fetch('/api/saas/me',{credentials:'same-origin'}).then(r=>r.ok?r.json():null).then(d=>{if(!d)return;form.elements.reporter_name.value=d.user?.full_name||'';form.elements.reporter_email.value=d.user?.email||'';form.elements.reporter_phone.value=d.user?.phone||'';const role=String(d.user?.role||'').toLowerCase();if(['owner','manager'].includes(role))form.elements.reporter_type.value=role;else if(role)form.elements.reporter_type.value='employee'}).catch(()=>{});
  form.onsubmit=async e=>{e.preventDefault();msg.className='gds-support-message';msg.textContent='Submitting securely…';const button=form.querySelector('.gds-support-submit');button.disabled=true;const fd=new FormData(form);const data=Object.fromEntries(fd.entries());delete data.files;data.confidential=form.elements.confidential.checked;data.anonymous=form.elements.anonymous.checked;if(data.anonymous)data.reporter_name='';const selectedFiles=[...(form.elements.files?.files||[])];try{const r=await fetch('/api/support/cases',{method:'POST',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify(data)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(r.status===429?'Please wait a moment before submitting another support request.':(d.error||'The support request could not be completed.'));let attachmentNote='';const attachments=[...selectedFiles];if(voiceBlob)attachments.push(new File([voiceBlob],`voice-note-${Date.now()}.webm`,{type:voiceBlob.type||'audio/webm'}));if(attachments.length){msg.textContent='Case created. Uploading evidence securely…';const evidence=new FormData();evidence.append('email',data.reporter_email||'');evidence.append('access_token',d.case.case_access_token||'');attachments.slice(0,5).forEach(file=>evidence.append('files',file));const ar=await fetch(`/api/support/cases/${encodeURIComponent(d.case.reference_code)}/attachments`,{method:'POST',credentials:'same-origin',body:evidence});const ad=await ar.json().catch(()=>({}));attachmentNote=ar.ok?`${ad.attachments?.length||0} attachment(s) secured with the case.`:`Case created, but attachments need retry: ${ad.error||'upload failed'}`;}const tokenNotice=d.case.case_access_token?`<div class="gds-support-token"><strong>Private case access key</strong><code>${esc(d.case.case_access_token)}</code><small>Save this key with your reference. It is shown once and can be used to match evidence or check case status without exposing your identity.</small></div>`:'';form.innerHTML=`<div class="gds-support-result"><b>Case received</b><p>Your case has been triaged and routed. Keep this reference and private access key.</p><code>${esc(d.case.reference_code)}</code>${tokenNotice}<p><strong>Priority:</strong> ${esc(d.case.severity)}<br><strong>Status:</strong> ${esc(d.case.status)}<br>${esc(d.case.triage_summary)}${attachmentNote?`<br><strong>Evidence:</strong> ${esc(attachmentNote)}`:''}</p></div><button class="gds-support-submit" type="button" data-new-case>Submit another case</button>`;form.querySelector('[data-new-case]').onclick=()=>location.reload()}catch(err){msg.className='gds-support-message error';msg.textContent=err.message;button.disabled=false}};
  function installTrustFooter(){
    if(document.querySelector('.sp-global-trust-footer'))return;
    const foot=document.createElement('section');foot.className='sp-global-trust-footer';foot.setAttribute('aria-label','Super Pro AI Office Manager trust and legal notice');
    foot.innerHTML=`<div><b>© 2026 Super Pro AI Office Manager. All rights reserved.</b><span>AI-assisted software · built with AI-assisted development · human review remains required for consequential decisions.</span></div><div><span>Security controls include authenticated access, role controls, audit logging and encrypted-transport architecture.</span><span class="sp-aws-status">AWS-ready deployment support · AWS certifications/badges are shown only when actually configured and independently verified.</span></div><nav><a href="/saas/terms.html">Terms</a><a href="/saas/privacy.html">Privacy</a><a href="/saas/trust-center.html">Trust Center</a><a href="/saas/subprocessors.html">Connected services</a></nav>`;
    document.body.append(foot);
  }
  installTrustFooter();

})();
