(() => {
  const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const adminApi=async(url,opt={})=>{const key=sessionStorage.getItem('fp-admin-key')||'';const r=await fetch(url,{credentials:'same-origin',headers:{'x-admin-key':key,'content-type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok){if(r.status===429)throw new Error('Too many requests for a moment. Please wait a few seconds and try again.');throw new Error(d.error||'The requested action could not be completed.')}return d};
  const toast=text=>{let box=$('#office-live-toasts');if(!box){box=document.createElement('div');box.id='office-live-toasts';box.className='office-live-toasts';document.body.append(box)}const e=document.createElement('div');e.className='office-live-toast';e.innerHTML=`<span>✓</span><div><b>Office update</b><small>${esc(text)}</small></div>`;box.append(e);requestAnimationFrame(()=>e.classList.add('show'));setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),250)},4800)};

  function installCopilot(){if($('#office-copilot'))return;const shell=document.createElement('div');shell.id='office-copilot';shell.className='office-copilot';shell.innerHTML=`<button class="office-copilot-launch" type="button"><span>AI</span><div><b>Office AI</b><small>Context + voice</small></div></button><section hidden><header><div><span>AI</span><div><b>Super Pro Office Co-pilot</b><small>Business operations guidance</small></div></div><button data-close type="button">×</button></header><div class="office-copilot-log"><article><b>How can I help?</b><p>Ask about the page you are on, a customer workflow, approvals, content, the business-only receptionist or where to find something.</p></article></div><form><button class="office-copilot-mic" type="button">◉</button><textarea rows="2" placeholder="Ask Office AI…" required></textarea><button type="submit">➜</button></form></section>`;document.body.append(shell);const launch=shell.querySelector('.office-copilot-launch'),panel=shell.querySelector('section'),log=shell.querySelector('.office-copilot-log'),ta=shell.querySelector('textarea');const open=(seed='')=>{panel.hidden=false;launch.hidden=true;if(seed)ta.value=seed;ta.focus()};const close=()=>{panel.hidden=true;launch.hidden=false};launch.onclick=()=>open();shell.querySelector('[data-close]').onclick=close;
    async function ask(q){q=String(q||'').trim();if(!q)return;log.insertAdjacentHTML('beforeend',`<article class="user"><b>You</b><p>${esc(q)}</p></article><article class="thinking"><b>Office AI</b><p>Thinking in your language…</p></article>`);log.scrollTop=log.scrollHeight;ta.value='';let result;try{result=await window.GDSProductGuide.answerAsync(q,`office:${document.querySelector('.nav.active')?.dataset.view||'dashboard'}`,'','auto')}catch{result=window.GDSProductGuide.answer(q,'workspace','')}log.querySelector('.thinking:last-of-type')?.remove();log.insertAdjacentHTML('beforeend',`<article><b>Office AI</b><p>${esc(result.text)}</p></article>`);log.scrollTop=log.scrollHeight}
    shell.querySelector('form').onsubmit=e=>{e.preventDefault();ask(ta.value)};const R=window.SpeechRecognition||window.webkitSpeechRecognition,mic=shell.querySelector('.office-copilot-mic');if(R){const r=new R();r.lang=navigator.language||'en-AU';r.interimResults=true;r.onresult=e=>{let q='';for(let i=e.resultIndex;i<e.results.length;i++)q+=e.results[i][0].transcript;ta.value=q;if(e.results[e.results.length-1].isFinal)setTimeout(()=>ask(q),120)};r.onstart=()=>mic.classList.add('listening');r.onend=()=>mic.classList.remove('listening');mic.onclick=()=>r.start()}else mic.disabled=true;
    window.GDSOfficeV11={...(window.GDSOfficeV11||{}),openCopilot:open,askCopilot:ask};
  }

  async function loadStaffChat(){const log=$('#office-staff-chat-log');if(!log)return;try{const d=await adminApi('/api/admin/staff-chat');log.innerHTML=d.messages?.length?d.messages.map(x=>`<article><div><b>${esc(x.sender_name)}</b><small>${new Date(x.created_at).toLocaleString()}</small></div><p>${esc(x.message)}</p></article>`).join(''):'<div class="empty-office-chat">No internal messages yet.</div>';log.scrollTop=log.scrollHeight}catch(e){log.innerHTML=`<div class="empty-office-chat">${esc(e.message)}</div>`}}

  function setupStaffChat(){const form=$('#office-staff-chat-form');if(form)form.onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(form));const b=form.querySelector('button');b.disabled=true;try{await adminApi('/api/admin/staff-chat',{method:'POST',body:JSON.stringify(f)});form.elements.message.value='';await loadStaffChat();toast('Internal staff message saved.')}catch(err){toast(err.message)}finally{b.disabled=false}};window.GDSOfficeV11={...(window.GDSOfficeV11||{}),loadStaffChat};}

  function setupButtons(){
    let viewBeforeStaffChat='dashboard';
    document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>{if(n.dataset.view!=='staffchat')viewBeforeStaffChat=n.dataset.view||viewBeforeStaffChat}));
    const leaveStaffChat=()=>document.querySelector(`.nav[data-view="${CSS.escape(viewBeforeStaffChat||'dashboard')}"]`)?.click();
    $('[data-office-chat-close]')?.addEventListener('click',leaveStaffChat);
    $('[data-office-chat-minimise]')?.addEventListener('click',leaveStaffChat);
    document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#staffchat-view')?.hidden)leaveStaffChat()});
    $('#office-copilot-top')?.addEventListener('click',()=>window.GDSOfficeV11?.openCopilot?.());
    $('#office-chat-top')?.addEventListener('click',()=>document.querySelector('.nav[data-view="staffchat"]')?.click());
    $('#office-help-top')?.addEventListener('click',()=>document.querySelector('.nav[data-view="help"]')?.click());
    $('#open-office-ai')?.addEventListener('click',()=>window.GDSOfficeV11?.openCopilot?.());
    $$('[data-office-ai-prompt]').forEach(b=>b.addEventListener('click',()=>window.GDSOfficeV11?.openCopilot?.(b.dataset.officeAiPrompt)));
    $$('[data-office-help]').forEach(b=>b.addEventListener('click',()=>{if(window.GDSSupport?.open)window.GDSSupport.open();else document.querySelector('.nav[data-view="help"]')?.click()}));
    $$('.panel-head').forEach(head=>{if(head.querySelector('.office-context-help')||head.closest('#dashboard-view'))return;const button=document.createElement('button');button.type='button';button.className='office-context-help';button.textContent='Ask AI about this';button.onclick=()=>window.GDSOfficeV11?.openCopilot?.(`Explain the ${head.querySelector('h2')?.textContent||'current'} section, what I can do here, and what needs approval.`);head.append(button)});
    const notice=$('#notice');if(notice)new MutationObserver(()=>{const t=notice.textContent.trim();if(t)toast(t)}).observe(notice,{childList:true,characterData:true,subtree:true});
  }

  function addDashboardCards(){const dash=$('#dashboard-view');if(!dash||$('#office-premium-cards'))return;const cards=document.createElement('div');cards.id='office-premium-cards';cards.className='office-premium-cards';cards.innerHTML='<article><span>AI</span><div><b>Office AI Co-pilot</b><small>Ask about any operation or page</small></div><button data-card-ai>Open</button></article><article><span>◎</span><div><b>Staff collaboration</b><small>Internal office discussion</small></div><button data-card-chat>Open</button></article><article><span>☎</span><div><b>Business-only receptionist</b><small>Dedicated business number · personal routing off</small></div><button data-card-phone>Configure</button></article><article><span>?</span><div><b>Help & governance</b><small>Support, complaints and policies</small></div><button data-card-help>Open</button></article>';dash.prepend(cards);cards.querySelector('[data-card-ai]').onclick=()=>window.GDSOfficeV11?.openCopilot?.();cards.querySelector('[data-card-chat]').onclick=()=>$('.nav[data-view="staffchat"]')?.click();cards.querySelector('[data-card-phone]').onclick=()=>$('.nav[data-view="receptionist"]')?.click();cards.querySelector('[data-card-help]').onclick=()=>$('.nav[data-view="help"]')?.click()}

  window.GDSOfficeV11={...(window.GDSOfficeV11||{}),toast};
  function install(){installCopilot();setupStaffChat();setupButtons();addDashboardCards()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
